//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.Pegasus_Modules.Common_Modules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalHomePageResourceresx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalHomePageResourceresx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.Pegasus_Modules.Common_Modules.GlobalHomePageResourceresx", typeof(GlobalHomePageResourceresx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/form/div[3]/div/div/div[1]/div/div/div/div[2]/div/div/div[1]/div/div[1]/div[1]/div/a.
        /// </summary>
        internal static string globalhomepage_ContextMenuIcon_Xpath {
            get {
                return ResourceManager.GetString("globalhomepage_ContextMenuIcon_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgbtnSave.
        /// </summary>
        internal static string globalhomepage_CopyAsInstructorCourse_CopyButton_locator {
            get {
                return ResourceManager.GetString("globalhomepage_CopyAsInstructorCourse_CopyButton_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtEndDate.
        /// </summary>
        internal static string globalhomepage_CopyAsInstructorCourse_EndDateLocator {
            get {
                return ResourceManager.GetString("globalhomepage_CopyAsInstructorCourse_EndDateLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to openModalPopupframe.
        /// </summary>
        internal static string globalhomepage_CopyAsInstructorCourse_iframe {
            get {
                return ResourceManager.GetString("globalhomepage_CopyAsInstructorCourse_iframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .messageBoardText.
        /// </summary>
        internal static string globalhomepage_CopyAsInstructorCourse_SuccefullMessage_Class {
            get {
                return ResourceManager.GetString("globalhomepage_CopyAsInstructorCourse_SuccefullMessage_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 364429.
        /// </summary>
        internal static string globalhomepage_CopyCourse_ContextMenu_Locator_ID {
            get {
                return ResourceManager.GetString("globalhomepage_CopyCourse_ContextMenu_Locator_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtProductName.
        /// </summary>
        internal static string globalhomepage_createCourse_locator_coursetitle_locator {
            get {
                return ResourceManager.GetString("globalhomepage_createCourse_locator_coursetitle_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnFinish.
        /// </summary>
        internal static string globalhomepage_createCourse_locator_Finish_locator {
            get {
                return ResourceManager.GetString("globalhomepage_createCourse_locator_Finish_locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnNext.
        /// </summary>
        internal static string globalhomepage_createCourse_searchbykeyword_nextbuton_locator_id {
            get {
                return ResourceManager.GetString("globalhomepage_createCourse_searchbykeyword_nextbuton_locator_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/div[1]/form/div[2]/div[2]/div/div[3]/div/span/div/div[2]/div/div[1]/div[2]/div/div[1]/input.
        /// </summary>
        internal static string globalhomepage_createCourse_SelectCourseinCatalog_locator_Xpath {
            get {
                return ResourceManager.GetString("globalhomepage_createCourse_SelectCourseinCatalog_locator_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtProductTextBook.
        /// </summary>
        internal static string globalhomepage_createcourse_serachkeyword_locator_id {
            get {
                return ResourceManager.GetString("globalhomepage_createcourse_serachkeyword_locator_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ctl7__ctl0__ctl0__ctl0__ctl0_btnSearchCatalog.
        /// </summary>
        internal static string globalhomepage_createcoursebutton_locator_id {
            get {
                return ResourceManager.GetString("globalhomepage_createcoursebutton_locator_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iframeCreateCourse.
        /// </summary>
        internal static string globalhomepage_createCourseiFrame_locator_iframename {
            get {
                return ResourceManager.GetString("globalhomepage_createCourseiFrame_locator_iframename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtCourseName.
        /// </summary>
        internal static string globalhomepage_EditCourseInfo_CourseTitle_Locator_ID {
            get {
                return ResourceManager.GetString("globalhomepage_EditCourseInfo_CourseTitle_Locator_ID", resourceCulture);
            }
        }
    }
}
