//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.Pegasus_Modules.Instructor_Modules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramAdminResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramAdminResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.Pegasus_Modules.Instructor_Modules.ProgramAdminResources", typeof(ProgramAdminResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnAddTemplate.
        /// </summary>
        internal static string ProgramAdmin_AddTemplate_AddAndCloseButton_Locator_ID {
            get {
                return ResourceManager.GetString("ProgramAdmin_AddTemplate_AddAndCloseButton_Locator_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/form/div[2]/table/tbody/tr[3]/td/table/tbody/tr[2]/td/div/table[2]/tbody/tr/td[1]/input.
        /// </summary>
        internal static string ProgramAdmin_AddTemplate_SelectTemplate_Locator_xPath {
            get {
                return ResourceManager.GetString("ProgramAdmin_AddTemplate_SelectTemplate_Locator_xPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to openModalPopupframe.
        /// </summary>
        internal static string ProgramAdmin_AddTemplatePopup_iframe_Locator_ID {
            get {
                return ResourceManager.GetString("ProgramAdmin_AddTemplatePopup_iframe_Locator_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aCT_5000000000000179.
        /// </summary>
        internal static string ProgramAdmin_ProgramName_Locator_ID {
            get {
                return ResourceManager.GetString("ProgramAdmin_ProgramName_Locator_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
    }
}
