//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegasus.Pages.Pegasus_Modules.Course_Materails_Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManageCourseMaterialsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageCourseMaterialsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegasus.Pages.Pegasus_Modules.Course_Materails_Page.ManageCourseMaterialsResource" +
                            "", typeof(ManageCourseMaterialsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/form/div/div[2]/div/div[7]/div/div[3]/button.
        /// </summary>
        internal static string MCM_ClosetheWizard_ReturntoMCM_Xpath {
            get {
                return ResourceManager.GetString("MCM_ClosetheWizard_ReturntoMCM_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [title*=&apos;Capítulo 01: Hola, ¿qué tal?&apos;].
        /// </summary>
        internal static string MCM_CoureMaterialWizard_SelectFolder_Locator_Css {
            get {
                return ResourceManager.GetString("MCM_CoureMaterialWizard_SelectFolder_Locator_Css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/form/div/div[1]/div/div[4]/div[1]/div/div/div/div/ul/li[3]/span/a[2]/span.
        /// </summary>
        internal static string MCM_CourseMaterailMainMenu_Icon_Locator {
            get {
                return ResourceManager.GetString("MCM_CourseMaterailMainMenu_Icon_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .insnavopttxt.
        /// </summary>
        internal static string MCM_CourseMaterailPullDownMenuIcon_Locator_ID {
            get {
                return ResourceManager.GetString("MCM_CourseMaterailPullDownMenuIcon_Locator_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to openModalPopupframe.
        /// </summary>
        internal static string MCM_CourseMaterailWizard_iFrame_Locator {
            get {
                return ResourceManager.GetString("MCM_CourseMaterailWizard_iFrame_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/form/div/div[2]/div/div[7]/div/div[2]/div/div/div[2]/div[1]/div/div[1]/div.
        /// </summary>
        internal static string MCM_CourseMaterialWizar_AddAssignmentTile_Locator_Xpath {
            get {
                return ResourceManager.GetString("MCM_CourseMaterialWizar_AddAssignmentTile_Locator_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [title*=&apos;STUDENT ACTIVITIES MANUAL&apos;].
        /// </summary>
        internal static string MCM_CourseMaterialWizard_SelectSourceFolderToAddContent_Locator_Css {
            get {
                return ResourceManager.GetString("MCM_CourseMaterialWizard_SelectSourceFolderToAddContent_Locator_Css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/form/div/div[3]/div[3]/div[2]/div/div[6]/button.
        /// </summary>
        internal static string MCM_CourseMaterilWizard_AddToMyCourseButton_XPATH_Loctator {
            get {
                return ResourceManager.GetString("MCM_CourseMaterilWizard_AddToMyCourseButton_XPATH_Loctator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addContent.
        /// </summary>
        internal static string MCM_CourseMaterilWizard_AddToMyCourseButtonCC_XPATH_Loctator {
            get {
                return ResourceManager.GetString("MCM_CourseMaterilWizard_AddToMyCourseButtonCC_XPATH_Loctator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [title*=&apos;Create Materials&apos;].
        /// </summary>
        internal static string MCM_CreateMaterails_Button_Css {
            get {
                return ResourceManager.GetString("MCM_CreateMaterails_Button_Css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifrmCoursePreview.
        /// </summary>
        internal static string MCM_CreateMaterialsFrame_iFrame {
            get {
                return ResourceManager.GetString("MCM_CreateMaterialsFrame_iFrame", resourceCulture);
            }
        }
    }
}
